#
# This file is part of Debuggery.
#
# Debuggery is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Debuggery is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Debuggery.  If not, see <http://www.gnu.org/licenses/>.
#

name: Debuggery
main: io.zachbr.debuggery.Debuggery
version: @version@
api-version: 1.13
author: Z750
website: https://github.com/zachbr/Debuggery
description: A small plugin designed to expose API values at runtime.
commands:
  debuggery:
    description: Debuggery!
    usage: /debuggery
  dblock:
    description: Returns block info
    usage: /dblock
  dchunk:
    description: Returns chunk info
    usage: /dchunk
  dentity:
    description: Returns entity info
    usage: /dentity
  ditem:
    description: Returns item info
    usage: /ditem
  dplayer:
    description: Returns player info
    usage: /dplayer
  dserver:
    description: Returns server info
    usage: /dserver
  dworld:
    description: Returns world info
    usage: /dworld
