name: Debuggery
main: io.zachbr.debuggery.DebuggeryJavaPlugin
version: 1.3.0-SNAPSHOT #TODO
api-version: 1.13
author: Z750
website: https://github.com/zachbr/Debuggery
description: A small plugin designed to expose API values at runtime.
commands:
  debuggery:
    description: Debuggery!
    usage: /debuggery
  dblock:
    description: Returns block info
    usage: /dblock
  dchunk:
    description: Returns chunk info
    usage: /dchunk
  ddebug:
    description: Returns internal system info
    usage: /ddebug
  dentity:
    description: Returns entity info
    usage: /dentity
  ditem:
    description: Returns item info
    usage: /ditem
  dplayer:
    description: Returns player info
    usage: /dplayer
  dserver:
    description: Returns server info
    usage: /dserver
  dworld:
    description: Returns world info
    usage: /dworld
